// File automatically generated by swift-bridge.
#include <stdbool.h>
bool __swift_bridge__$call_memory_with_default_tunables(void);
bool __swift_bridge__$call_memory_with_limited_static_tunables(void);
bool __swift_bridge__$call_memory_with_dynamic_tunables(void);


