// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
int32_t __swift_bridge__$call_wasmer(void);
bool __swift_bridge__$call(struct __private__FfiSlice wasm_program);


